# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
        - /release-.*/

    docker:
      # specify the version you desire here
      - image: circleci/node:8.11-stretch
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:   # (2)
          # docker_layer_caching: true # (3)
          version: 17.03.0-ce

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      # - run:
      #     name: Install Docker client
      #     command: |
      #       set -x
      #       VER="17.03.0-ce"
      #       curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
      #       tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      #       mv /tmp/docker/* /usr/bin

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t  phucpnt/kasru:$TAG -t  phucpnt/kasru:latest .      # (4)
          docker login -u $DOCKER_USER -p $DOCKER_PASS         # (5)
          docker push phucpnt/kasru:$TAG
          docker push phucpnt/kasru:latest
      - add_ssh_keys:
          fingerprints:
            - "8a:c9:46:78:08:c1:37:7f:79:f6:22:6b:b1:5b:48:20"
      - run:
          name: Deploy to server
          command:
            ssh $SSH_USER@$SSH_HOST "cd $SSH_FOLDER && docker-compose stop kasru && docker-compose update kasru && docker-compose up kasru"

